# Site settings
title: Jekyll for Web Designers
description: "Companion blog to the lynda.com course, Jekyll for Web Designers. This site is designed to present Jekyll to web designers in a clear, concise way, and provide a resource and reference for those that are new to Jekyll."
baseurl: "/jekyll-for-designers" 
url: "http://jameswillweb.github.io/jekyll-for-designers" 
tagline: A basic guide to Jekyll

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
