#!/bin/sh
# Make v1 or v2 the homepage.
#   ./switch.sh v1   -> classic
#   ./switch.sh v2   -> "thinks outside the box"
# Edit v1/index.html or v2/index.html, never the root index.html: it's generated.
# Both versions stay live at /v1/ and /v2/ (noindex, canonical to /), so switching never breaks a link.
set -e
cd "$(dirname "$0")"

version="$1"
if [ "$version" != "v1" ] && [ "$version" != "v2" ]; then
	echo "usage: ./switch.sh v1|v2" >&2
	echo "current homepage: $(sed -n 's/.*generated by switch.sh from \([^ ]*\)\/index.html.*/\1/p' index.html 2>/dev/null)" >&2
	exit 1
fi

src="$version/index.html"
grep -q 'content="noindex, follow"' "$src" || { echo "$src is missing its robots meta; refusing to guess" >&2; exit 1; }

sed \
	-e '/<!--Version page: switch.sh turns this into an indexable homepage copy-->/d' \
	-e 's#<meta name="robots" content="noindex, follow">#<meta name="robots" content="index, follow, max-image-preview:large">#' \
	"$src" |
awk -v note="<!-- generated by switch.sh from $version/index.html. Edit that file, then run ./switch.sh $version -->" \
	'{ print } NR == 1 { print note }' > index.html

echo "homepage is now $version"
